version: '3'

services:
  web:
    build: .
    restart: always
    ports:
    - 8000:80
    tty: true
    volumes:
    - ./logs:/var/log/nginx
    - ./src/component:/home/components/helloworld
    - ./src/template:/home/templates/joomlapure
    - ./dev_package:/home/dev
    depends_on:
    - db
    environment:
      SITE_NAME: ${SITE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_HOST: ${MYSQL_DB_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  db:
    image: mysql:5.7
    command: mysqld
    restart: always
    hostname: ${MYSQL_DB_HOST}
    domainname: ${MYSQL_DB_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    tty: true
