version: '3'

services:
  web:
    build:
      context: .
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    ports:
    - 8000:80
    tty: true
    volumes:
    - ./logs:/var/log/nginx
    depends_on:
    - db
    - cache

  db:
    image: mysql:5.7
    command: mysqld
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
    - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    tty: true

  cache:
    image: bitnami/memcached
    ports:
    - 11211:11211
    environment:
    - MEMCACHED_CACHE_SIZE=${MEMCACHED_CACHE_SIZE}
